### ISSUE TITLE
Conditional jumps and uninitialized values detected

### ISSUE THREAD

**Issue by xhelp00** [xhelp00/cub3d#9]
Tried to run valgrind on mac just for fun, no leaks detected but other errors yes.
We should decide if and how to handle them :) also have to check leaks on linux to be sure...
![image](https://github.com/xhelp00/cub3d/assets/111277585/5e02403d-3d39-4f26-b173-618cc5f3d41d)

**Comment by AntessTerra** [comment]
Should be fixed now
